# brew
eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"
export HOMEBREW_NO_ENV_HINTS=1

# pnpm
export NODE_NO_WARNINGS=1
export PNPM_HOME="$HOME/.local/share/pnpm"
[ -d "$PNPM_HOME" ] && PATH="$PNPM_HOME:$PATH"

# ls
ignore_pattern="~/.cache|~/.npm|node_modules"
eza_args="--icons --group-directories-first --width 120"
alias la="eza $eza_args --all"
alias ls="eza $eza_args --git-ignore --ignore-glob='$ignore_pattern'"
alias tree="eza $eza_args --tree --git-ignore --ignore-glob='$ignore_pattern'"

# navigation
alias ..='cd ..'
alias rm='rm -rf'
cd() {
    builtin cd "$@" && eza $eza_args
}

# tools
alias vi="nvim"
alias k="k9s --headless -c ns"
alias ssh-dev="ssh $USER@dev.mp281x.xyz"

# docker
ps() {
	docker ps --all --format '{{json .}}' | jq -s 'map({
		name: .Names,
		status: .Status,
  	image: .Image,
  	ports: (
    	.Ports
    	| split(", ")
    	| map(select(test("->")))
    	| map(capture("0.0.0.0:(?<hostPort>[0-9]+)->(?<containerPort>[0-9]+)"))
    	| map(.hostPort + ":" + .containerPort)
  	)
	})'
}

# claude code
alias c="claude"
alias cc="claude --continue"

# update globally installed packages
alias ii="npm update -g"

# pnpm
alias i="pnpm update --recursive --no-save"
alias pnpx="pnpm dlx"

# git
alias g="gitui"
export REGISTRY_TOKEN=$(gh auth token)
gl() {
	if [ $# -eq 0 ]; then gh repo list --json name,owner | jq -r '[.[] | "\(.owner.login)/\(.name)"]';
  else gh repo list "$1" --json name,owner | jq -r '[.[] | "\(.owner.login)/\(.name)"]'; fi
}
gc() {
	if [[ $1 == *"/"* ]]; then git clone --quiet "https://github.com/$1.git";
  else git clone --quiet "https://github.com/$(git config --get user.name)/$1.git"; fi
}
gr() {
	git fetch --prune && git branch -r | awk "{print \$1}" | egrep -v -f /dev/fd/0 <(git branch -vv | grep origin) | awk "{print \$1}" | xargs git branch -D
}

# wsl
alias reboot="wsl.exe --shutdown"
alias restart="wsl.exe --shutdown"

# disable the rest of the configuration for non interactive scripts
[[ $- == *i* ]] || return

# clean files
rm -f ~/.local/state/nvim/shada/main.shada
rm -f ~/.sudo_as_admin_successful
rm -f ~/.bash_logout
rm -f ~/.wget-hsts
rm -f ~/.profile

# shell history
shopt -s histappend
export HISTSIZE=500
export HISTFILESIZE=10000
export HISTCONTROL=erasedups:ignoredups:ignorespace

# autocomplete
bind 'TAB:menu-complete'
bind "set completion-ignore-case on";

# change cursor shape based on the current mode
export PROMPT_COMMAND='history -a && echo -ne "\033[5 q"'
bind 'set vi-cmd-mode-string \1\e[1 q\2'
bind 'set vi-ins-mode-string \1\e[5 q\2'

# starship
eval "$(starship init bash)"; eza $eza_args

# fzf
source "$(brew --prefix)/opt/fzf/shell/key-bindings.bash"
export FZF_DEFAULT_OPTS="--no-hscroll --no-mouse --reverse --no-info --border=none"

# enable vim mode
export EDITOR=nvim
set -o vi
bind 'set keyseq-timeout 10'
bind 'set show-mode-in-prompt on'
